// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0kpL3s3XS6bH423Nekf00V2-iHJUjzGY',
    appId: '1:65559190805:web:1040b86702c3c630fa5d1c',
    messagingSenderId: '65559190805',
    projectId: 'cchat-app-165a7',
    authDomain: 'cchat-app-165a7.firebaseapp.com',
    storageBucket: 'cchat-app-165a7.firebasestorage.app',
    measurementId: 'G-SQH6C92QMB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHXqEpqzHCFeRzvg5Mm6ql_RBihuCukZ0',
    appId: '1:65559190805:android:3322fad42fde3f40fa5d1c',
    messagingSenderId: '65559190805',
    projectId: 'cchat-app-165a7',
    storageBucket: 'cchat-app-165a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjAidpzYtoXt3BaLAv3H47fEZvLQfDdTA',
    appId: '1:65559190805:ios:a2cc109051c67bd4fa5d1c',
    messagingSenderId: '65559190805',
    projectId: 'cchat-app-165a7',
    storageBucket: 'cchat-app-165a7.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjAidpzYtoXt3BaLAv3H47fEZvLQfDdTA',
    appId: '1:65559190805:ios:a2cc109051c67bd4fa5d1c',
    messagingSenderId: '65559190805',
    projectId: 'cchat-app-165a7',
    storageBucket: 'cchat-app-165a7.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0kpL3s3XS6bH423Nekf00V2-iHJUjzGY',
    appId: '1:65559190805:web:04a6c5f7c170cb22fa5d1c',
    messagingSenderId: '65559190805',
    projectId: 'cchat-app-165a7',
    authDomain: 'cchat-app-165a7.firebaseapp.com',
    storageBucket: 'cchat-app-165a7.firebasestorage.app',
    measurementId: 'G-6T7Y6MD5Q5',
  );
}
